#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellNetixApps.Source.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tools")]
	public partial class ToolsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ToolsDataContext() : 
				base(global::CellNetixApps.Properties.Settings.Default.tools_testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ToolsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PP_Get_Case_Details")]
		public ISingleResult<SP_PP_Get_Case_DetailsResult> SP_PP_Get_Case_Details([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acc_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), acc_id);
			return ((ISingleResult<SP_PP_Get_Case_DetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PP_Get_Case_Details_Portal")]
		public ISingleResult<SP_PP_Get_Case_Details_PortalResult> SP_PP_Get_Case_Details_Portal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acc_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), acc_id);
			return ((ISingleResult<SP_PP_Get_Case_Details_PortalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stprc_clntx_pathologist_open_orders")]
		public ISingleResult<stprc_clntx_pathologist_open_ordersResult> stprc_clntx_pathologist_open_orders([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> path_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), path_id);
			return ((ISingleResult<stprc_clntx_pathologist_open_ordersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PP_Get_Case_Results")]
		public ISingleResult<SP_PP_Get_Case_ResultsResult> SP_PP_Get_Case_Results([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acc_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), acc_id);
			return ((ISingleResult<SP_PP_Get_Case_ResultsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PP_Get_Gross_desc")]
		public ISingleResult<SP_PP_Get_Gross_descResult> SP_PP_Get_Gross_desc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acc_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), acc_id);
			return ((ISingleResult<SP_PP_Get_Gross_descResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stprc_clntx_slide_labels_by_slide_id")]
		public ISingleResult<stprc_clntx_slide_labels_by_slide_idResult> stprc_clntx_slide_labels_by_slide_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slide_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slide_id);
			return ((ISingleResult<stprc_clntx_slide_labels_by_slide_idResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stprc_clntx_blocks_batch_id")]
		public int stprc_clntx_blocks_batch_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string blocks, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> batch_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), blocks, batch_id);
			batch_id = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PP_Get_Path_Assigned_Cases")]
		public ISingleResult<SP_PP_Get_Path_Assigned_CasesResult> SP_PP_Get_Path_Assigned_Cases([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Path_ID", DbType="Int")] System.Nullable<int> path_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), path_ID);
			return ((ISingleResult<SP_PP_Get_Path_Assigned_CasesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_clntx_get_level_info", IsComposable=true)]
		public string fn_clntx_get_level_info([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> start_level, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> total_levels)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start_level, total_levels).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stprc_clntx_set_acc_order_status_web")]
		public int stprc_clntx_set_acc_order_status_web([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acc_order_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> personnel_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), acc_order_id, status, personnel_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stprc_clntx_pp_image_insert")]
		public int stprc_clntx_pp_image_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> case_image_scanner_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pp_user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> include_in_report)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), case_image_scanner_id, description, pp_user_id, include_in_report);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_PP_Get_Case_DetailsResult
	{
		
		private string _Accession_Number;
		
		private string _Case_Priority;
		
		private string _Revenue_Center;
		
		private string _Primary_Referring_Physician;
		
		private string _Facility;
		
		private System.Nullable<char> _Status_Final;
		
		private string _Assigned_Pathologist;
		
		public SP_PP_Get_Case_DetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Accession Number]", Storage="_Accession_Number", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Accession_Number
		{
			get
			{
				return this._Accession_Number;
			}
			set
			{
				if ((this._Accession_Number != value))
				{
					this._Accession_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Case Priority]", Storage="_Case_Priority", DbType="Char(10)")]
		public string Case_Priority
		{
			get
			{
				return this._Case_Priority;
			}
			set
			{
				if ((this._Case_Priority != value))
				{
					this._Case_Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Revenue Center]", Storage="_Revenue_Center", DbType="VarChar(92)")]
		public string Revenue_Center
		{
			get
			{
				return this._Revenue_Center;
			}
			set
			{
				if ((this._Revenue_Center != value))
				{
					this._Revenue_Center = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Referring Physician]", Storage="_Primary_Referring_Physician", DbType="VarChar(60)")]
		public string Primary_Referring_Physician
		{
			get
			{
				return this._Primary_Referring_Physician;
			}
			set
			{
				if ((this._Primary_Referring_Physician != value))
				{
					this._Primary_Referring_Physician = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facility", DbType="VarChar(80)")]
		public string Facility
		{
			get
			{
				return this._Facility;
			}
			set
			{
				if ((this._Facility != value))
				{
					this._Facility = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Status Final]", Storage="_Status_Final", DbType="Char(1)")]
		public System.Nullable<char> Status_Final
		{
			get
			{
				return this._Status_Final;
			}
			set
			{
				if ((this._Status_Final != value))
				{
					this._Status_Final = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Assigned Pathologist]", Storage="_Assigned_Pathologist", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Assigned_Pathologist
		{
			get
			{
				return this._Assigned_Pathologist;
			}
			set
			{
				if ((this._Assigned_Pathologist != value))
				{
					this._Assigned_Pathologist = value;
				}
			}
		}
	}
	
	public partial class SP_PP_Get_Case_Details_PortalResult
	{
		
		private string _Patient;
		
		private string _Priority;
		
		private string _RefMD;
		
		public SP_PP_Get_Case_Details_PortalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient", DbType="VarChar(60)")]
		public string Patient
		{
			get
			{
				return this._Patient;
			}
			set
			{
				if ((this._Patient != value))
				{
					this._Patient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Char(10)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefMD", DbType="VarChar(60)")]
		public string RefMD
		{
			get
			{
				return this._RefMD;
			}
			set
			{
				if ((this._RefMD != value))
				{
					this._RefMD = value;
				}
			}
		}
	}
	
	public partial class stprc_clntx_pathologist_open_ordersResult
	{
		
		private string _accession_no;
		
		private string _code;
		
		private string _description;
		
		private System.Nullable<byte> _quantity;
		
		private string _source;
		
		private string _status;
		
		private string _priority;
		
		private string _lab_department;
		
		private string _lab_dept_worklist;
		
		private System.Nullable<System.DateTime> _ordered_date;
		
		private string _ordered_by;
		
		private System.Nullable<System.DateTime> _completed_date;
		
		private string _completed_by;
		
		private System.Nullable<char> _bill;
		
		private string _service_code;
		
		public stprc_clntx_pathologist_open_ordersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accession_no", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string accession_no
		{
			get
			{
				return this._accession_no;
			}
			set
			{
				if ((this._accession_no != value))
				{
					this._accession_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(80)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="TinyInt")]
		public System.Nullable<byte> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="VarChar(130)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this._source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="VarChar(18)")]
		public string priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this._priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lab_department", DbType="VarChar(30)")]
		public string lab_department
		{
			get
			{
				return this._lab_department;
			}
			set
			{
				if ((this._lab_department != value))
				{
					this._lab_department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lab_dept_worklist", DbType="VarChar(40)")]
		public string lab_dept_worklist
		{
			get
			{
				return this._lab_dept_worklist;
			}
			set
			{
				if ((this._lab_dept_worklist != value))
				{
					this._lab_dept_worklist = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordered_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> ordered_date
		{
			get
			{
				return this._ordered_date;
			}
			set
			{
				if ((this._ordered_date != value))
				{
					this._ordered_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordered_by", DbType="VarChar(60)")]
		public string ordered_by
		{
			get
			{
				return this._ordered_by;
			}
			set
			{
				if ((this._ordered_by != value))
				{
					this._ordered_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> completed_date
		{
			get
			{
				return this._completed_date;
			}
			set
			{
				if ((this._completed_date != value))
				{
					this._completed_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed_by", DbType="VarChar(60)")]
		public string completed_by
		{
			get
			{
				return this._completed_by;
			}
			set
			{
				if ((this._completed_by != value))
				{
					this._completed_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill", DbType="Char(1)")]
		public System.Nullable<char> bill
		{
			get
			{
				return this._bill;
			}
			set
			{
				if ((this._bill != value))
				{
					this._bill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_code", DbType="VarChar(15)")]
		public string service_code
		{
			get
			{
				return this._service_code;
			}
			set
			{
				if ((this._service_code != value))
				{
					this._service_code = value;
				}
			}
		}
	}
	
	public partial class SP_PP_Get_Case_ResultsResult
	{
		
		private string _Header;
		
		private string _Result;
		
		public SP_PP_Get_Case_ResultsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Header", DbType="VarChar(80)")]
		public string Header
		{
			get
			{
				return this._Header;
			}
			set
			{
				if ((this._Header != value))
				{
					this._Header = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class SP_PP_Get_Gross_descResult
	{
		
		private string _GrossDescription;
		
		public SP_PP_Get_Gross_descResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossDescription", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string GrossDescription
		{
			get
			{
				return this._GrossDescription;
			}
			set
			{
				if ((this._GrossDescription != value))
				{
					this._GrossDescription = value;
				}
			}
		}
	}
	
	public partial class stprc_clntx_slide_labels_by_slide_idResult
	{
		
		private System.Nullable<int> _order_id;
		
		private int _case_id;
		
		private string _accession_no;
		
		private string _accession_no_sans_check_char;
		
		private string _consult_accession_no;
		
		private string _specimen_desc;
		
		private string _procedure_code;
		
		private string _procedure_label_desc;
		
		private string _specimen_label;
		
		private string _block_label;
		
		private System.Nullable<short> _slide_label;
		
		private string _case_type;
		
		private System.Nullable<byte> _institution;
		
		private string _pt_name;
		
		private string _encoded_material_id;
		
		private string _rec_type;
		
		private System.Nullable<char> _acc_catg;
		
		private string _specimen_code;
		
		private string _facility_code;
		
		private string _facility_name;
		
		private System.Nullable<System.DateTime> _spec_coll_date;
		
		private System.Nullable<System.DateTime> _spec_recv_date;
		
		private System.Nullable<System.DateTime> _case_created_date;
		
		private System.Nullable<System.DateTime> _order_created_date;
		
		private string _patient_last_name;
		
		private string _patient_first_name;
		
		private string _rev_center_code;
		
		private string _level_info;
		
		private System.DateTime _Column1;
		
		public stprc_clntx_slide_labels_by_slide_idResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int")]
		public System.Nullable<int> order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this._order_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", DbType="Int NOT NULL")]
		public int case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this._case_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accession_no", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string accession_no
		{
			get
			{
				return this._accession_no;
			}
			set
			{
				if ((this._accession_no != value))
				{
					this._accession_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accession_no_sans_check_char", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string accession_no_sans_check_char
		{
			get
			{
				return this._accession_no_sans_check_char;
			}
			set
			{
				if ((this._accession_no_sans_check_char != value))
				{
					this._accession_no_sans_check_char = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consult_accession_no", DbType="VarChar(100)")]
		public string consult_accession_no
		{
			get
			{
				return this._consult_accession_no;
			}
			set
			{
				if ((this._consult_accession_no != value))
				{
					this._consult_accession_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specimen_desc", DbType="VarChar(80)")]
		public string specimen_desc
		{
			get
			{
				return this._specimen_desc;
			}
			set
			{
				if ((this._specimen_desc != value))
				{
					this._specimen_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedure_code", DbType="VarChar(15)")]
		public string procedure_code
		{
			get
			{
				return this._procedure_code;
			}
			set
			{
				if ((this._procedure_code != value))
				{
					this._procedure_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedure_label_desc", DbType="VarChar(80)")]
		public string procedure_label_desc
		{
			get
			{
				return this._procedure_label_desc;
			}
			set
			{
				if ((this._procedure_label_desc != value))
				{
					this._procedure_label_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specimen_label", DbType="VarChar(5)")]
		public string specimen_label
		{
			get
			{
				return this._specimen_label;
			}
			set
			{
				if ((this._specimen_label != value))
				{
					this._specimen_label = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_block_label", DbType="VarChar(5)")]
		public string block_label
		{
			get
			{
				return this._block_label;
			}
			set
			{
				if ((this._block_label != value))
				{
					this._block_label = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slide_label", DbType="SmallInt")]
		public System.Nullable<short> slide_label
		{
			get
			{
				return this._slide_label;
			}
			set
			{
				if ((this._slide_label != value))
				{
					this._slide_label = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_type", DbType="VarChar(30)")]
		public string case_type
		{
			get
			{
				return this._case_type;
			}
			set
			{
				if ((this._case_type != value))
				{
					this._case_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_institution", DbType="TinyInt")]
		public System.Nullable<byte> institution
		{
			get
			{
				return this._institution;
			}
			set
			{
				if ((this._institution != value))
				{
					this._institution = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pt_name", DbType="VarChar(80)")]
		public string pt_name
		{
			get
			{
				return this._pt_name;
			}
			set
			{
				if ((this._pt_name != value))
				{
					this._pt_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_encoded_material_id", DbType="VarChar(25)")]
		public string encoded_material_id
		{
			get
			{
				return this._encoded_material_id;
			}
			set
			{
				if ((this._encoded_material_id != value))
				{
					this._encoded_material_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_type", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string rec_type
		{
			get
			{
				return this._rec_type;
			}
			set
			{
				if ((this._rec_type != value))
				{
					this._rec_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_catg", DbType="Char(1)")]
		public System.Nullable<char> acc_catg
		{
			get
			{
				return this._acc_catg;
			}
			set
			{
				if ((this._acc_catg != value))
				{
					this._acc_catg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specimen_code", DbType="VarChar(15)")]
		public string specimen_code
		{
			get
			{
				return this._specimen_code;
			}
			set
			{
				if ((this._specimen_code != value))
				{
					this._specimen_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility_code", DbType="VarChar(15)")]
		public string facility_code
		{
			get
			{
				return this._facility_code;
			}
			set
			{
				if ((this._facility_code != value))
				{
					this._facility_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility_name", DbType="VarChar(80)")]
		public string facility_name
		{
			get
			{
				return this._facility_name;
			}
			set
			{
				if ((this._facility_name != value))
				{
					this._facility_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spec_coll_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> spec_coll_date
		{
			get
			{
				return this._spec_coll_date;
			}
			set
			{
				if ((this._spec_coll_date != value))
				{
					this._spec_coll_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spec_recv_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> spec_recv_date
		{
			get
			{
				return this._spec_recv_date;
			}
			set
			{
				if ((this._spec_recv_date != value))
				{
					this._spec_recv_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> case_created_date
		{
			get
			{
				return this._case_created_date;
			}
			set
			{
				if ((this._case_created_date != value))
				{
					this._case_created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> order_created_date
		{
			get
			{
				return this._order_created_date;
			}
			set
			{
				if ((this._order_created_date != value))
				{
					this._order_created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_last_name", DbType="VarChar(30)")]
		public string patient_last_name
		{
			get
			{
				return this._patient_last_name;
			}
			set
			{
				if ((this._patient_last_name != value))
				{
					this._patient_last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_first_name", DbType="VarChar(30)")]
		public string patient_first_name
		{
			get
			{
				return this._patient_first_name;
			}
			set
			{
				if ((this._patient_first_name != value))
				{
					this._patient_first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rev_center_code", DbType="VarChar(10)")]
		public string rev_center_code
		{
			get
			{
				return this._rev_center_code;
			}
			set
			{
				if ((this._rev_center_code != value))
				{
					this._rev_center_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_info", DbType="VarChar(20)")]
		public string level_info
		{
			get
			{
				return this._level_info;
			}
			set
			{
				if ((this._level_info != value))
				{
					this._level_info = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime NOT NULL")]
		public System.DateTime Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class SP_PP_Get_Path_Assigned_CasesResult
	{
		
		private string _accession_no;
		
		private string _Accession_Number;
		
		private string _Case_Type;
		
		private string _Currently_Assigned_to;
		
		private System.Nullable<System.DateTime> _Received;
		
		private string _Case_Status;
		
		private string _hold;
		
		private string _Priority;
		
		private string _patient_name;
		
		private string _MRN;
		
		private string _refmd_name;
		
		private string _Primary_Specimen;
		
		public SP_PP_Get_Path_Assigned_CasesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accession_no", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string accession_no
		{
			get
			{
				return this._accession_no;
			}
			set
			{
				if ((this._accession_no != value))
				{
					this._accession_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Accession Number]", Storage="_Accession_Number", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Accession_Number
		{
			get
			{
				return this._Accession_Number;
			}
			set
			{
				if ((this._Accession_Number != value))
				{
					this._Accession_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Case Type]", Storage="_Case_Type", DbType="VarChar(30)")]
		public string Case_Type
		{
			get
			{
				return this._Case_Type;
			}
			set
			{
				if ((this._Case_Type != value))
				{
					this._Case_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Currently Assigned to]", Storage="_Currently_Assigned_to", DbType="VarChar(60)")]
		public string Currently_Assigned_to
		{
			get
			{
				return this._Currently_Assigned_to;
			}
			set
			{
				if ((this._Currently_Assigned_to != value))
				{
					this._Currently_Assigned_to = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Received", DbType="DateTime")]
		public System.Nullable<System.DateTime> Received
		{
			get
			{
				return this._Received;
			}
			set
			{
				if ((this._Received != value))
				{
					this._Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Case Status]", Storage="_Case_Status", DbType="VarChar(86)")]
		public string Case_Status
		{
			get
			{
				return this._Case_Status;
			}
			set
			{
				if ((this._Case_Status != value))
				{
					this._Case_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hold", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string hold
		{
			get
			{
				return this._hold;
			}
			set
			{
				if ((this._hold != value))
				{
					this._hold = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_name", DbType="VarChar(60)")]
		public string patient_name
		{
			get
			{
				return this._patient_name;
			}
			set
			{
				if ((this._patient_name != value))
				{
					this._patient_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRN", DbType="VarChar(30)")]
		public string MRN
		{
			get
			{
				return this._MRN;
			}
			set
			{
				if ((this._MRN != value))
				{
					this._MRN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refmd_name", DbType="VarChar(60)")]
		public string refmd_name
		{
			get
			{
				return this._refmd_name;
			}
			set
			{
				if ((this._refmd_name != value))
				{
					this._refmd_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Specimen", DbType="VarChar(80)")]
		public string Primary_Specimen
		{
			get
			{
				return this._Primary_Specimen;
			}
			set
			{
				if ((this._Primary_Specimen != value))
				{
					this._Primary_Specimen = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
